### ISSUE TITLE
自动打卡的时间，是根据本地还是网络

### ISSUE THREAD

**Issue by BrilliantYezi** [LuckyPray/XAutoDaily#10]
模块的自动打卡是根据本地的时间，还是网络时间？

**Comment by teble** [comment]
从rc 10开始就是根据网络时间了

**Comment by teble** [comment]
> > 从rc 10开始就是根据网络时间了
> 
> 但是它似乎并不能在准确的时间执行打卡任务

有没有一种可能，百度时间跟具体服务的服务器时间不一致

**Comment by BrilliantYezi** [comment]
> 

我有进行过尝试，凌晨23:50的时候，就打开QQ开始等，但是到了00点并没有打卡。直到我点击了立即打卡，它才开始签到打卡。

甚至到了白天，它会时不时弹出，正在打卡签到的提示。

主要我是想试试那个群打卡。我想在群里抢首签，但是模块到时间无法自动打卡的问题，导致并不能这样做。

如果我只选群打卡，点击立即打卡，也无法瞬间打卡完成，而是有较高的延迟

**Comment by teble** [comment]
> > 
> 
> 我有进行过尝试，凌晨23:50的时候，就打开QQ开始等，但是到了00点并没有打卡。直到我点击了立即打卡，它才开始签到打卡。
> 
> 甚至到了白天，它会时不时弹出，正在打卡签到的提示。
> 
> 主要我是想试试那个群打卡。我想在群里抢首签，但是模块到时间无法自动打卡的问题，导致并不能这样做。
> 
> 如果我只选群打卡，点击立即打卡，也无法瞬间打卡完成，而是有较高的延迟

是否能导出一下日志文件压缩包给我看一下

**Comment by BrilliantYezi** [comment]
> > > 
> > 
> > 
> > 我有进行过尝试，凌晨23:50的时候，就打开QQ开始等，但是到了00点并没有打卡。直到我点击了立即打卡，它才开始签到打卡。
> > 甚至到了白天，它会时不时弹出，正在打卡签到的提示。
> > 主要我是想试试那个群打卡。我想在群里抢首签，但是模块到时间无法自动打卡的问题，导致并不能这样做。
> > 如果我只选群打卡，点击立即打卡，也无法瞬间打卡完成，而是有较高的延迟
> 
> 是否能导出一下日志文件压缩包给我看一下

我发群组里了，作者大大

**Comment by teble** [comment]
任务反复执行，目前无法定位原因等待后续跟进
0点整不执行问题已经大致找到了

**Comment by BrilliantYezi** [comment]
> 任务反复执行，目前无法定位原因等待后续跟进 0点整不执行问题已经大致找到了

好的，大大辛苦了。
