### ISSUE TITLE
[Bug]在QQ9.0.75上无法获得"群组列表"并发生闪退

### ISSUE THREAD

**Issue by Arce0416** [LuckyPray/XAutoDaily#100]
**一.复现步骤：**   
①打开QQ内的"XAutoDaily"，并开启总开关   
②打开"签到设置"，后打开了"群打卡"，"群续火"开关  
③进入"群打卡"，"群续火"内页，在内页发生频繁闪退(刷新(向下滑动)闪退，打开闪退(概率)，单击"变量"闪退)   
④使用LogFox抓取了"群打卡"和"群续火"模块的日志(单击"变量")    

**二.预期行为与实际行为**    
①预期行为：正常打开内页无闪退，单击"变量"正常打开"群组列表"     
②实际行为：同"第一标题第③栏"     

**三、使用的各应用版本**    
①QQ：QQ9.0.75(官网最新)
②Xp模块：1.QAuxiliary(测试时已停用)2.XAutoDaily3.0.26-fix    
③Xp框架：ONPatch0.6.1
④系统版本：Android 13, coloros 13      

**四、日志**
[日志.zip](https://github.com/user-attachments/files/16344994/default.zip)

**Comment by teble** [comment]
已知问题，75行为更改已修复还未提交。等续火那边修好了才会发版，还需要一点时间

**Comment by Arce0416** [comment]
ok

**Comment by teble** [comment]
3.0.27已修复
