### ISSUE TITLE
群打卡和点赞执行失败

### ISSUE THREAD

**Issue by junzhaoei** [LuckyPray/XAutoDaily#104]
昨天还能用的，今天凌晨显示执行失败，重试了好几次也依旧这样，系统是澎湃1.0.17.0
![Screenshot_2024-08-22-23-23-01-897_com tencent mobileqq](https://github.com/user-attachments/assets/6569c014-c353-4e00-bf15-f86764e1aad0)

**Comment by EatHatsuneShallots** [comment]
日志呢

**Comment by junzhaoei** [comment]
![Uploading Screenshot_2024-08-23-05-51-46-994_bin.mt.plus.jpg…]()
![Uploading Screenshot_2024-08-23-05-52-09-452_bin.mt.plus.jpg…]()
![Uploading Screenshot_2024-08-23-05-52-27-264_bin.mt.plus.jpg…]()

**Comment by junzhaoei** [comment]
> 日志呢

![Screenshot_2024-08-23-05-51-46-994_bin mt plus](https://github.com/user-attachments/assets/c095ff98-7dc6-4bc2-a914-f22f39858d9b)
![Screenshot_2024-08-23-05-52-09-452_bin mt plus](https://github.com/user-attachments/assets/68b331ac-3d65-4e04-8dbe-d2d4b00cadc4)
![Screenshot_2024-08-23-05-52-27-264_bin mt plus](https://github.com/user-attachments/assets/462cbd1f-25a1-489c-a2b0-b0e8de198147)

**Comment by EatHatsuneShallots** [comment]
看起来像是 Token 或（和）Cookie 无法获取、没有及时刷新等

**Comment by junzhaoei** [comment]
> 看起来像是 Token 或（和）Cookie 无法获取、没有及时刷新等 对了 QQ 版本提供一下

qq版本:9.0.75

**Comment by teble** [comment]
我猜手动重置一次就好了，凌晨的时候可能会由于手机休眠冻结现成导致协议请求回调超时抛出异常。
当初设计的时候过于谨慎，担心某些任务会过期导致请求失败导致无限重试的情况发生，所以添加了一个连续失败3次会在当天冻结执行的逻辑。但是如果仅仅是超时导致应该被忽略掉，等待后续执行反复重试

**Comment by teble** [comment]
当然，超时的原因可能不止这一种，也有可能是由于qq内部协议发送由于某种原因被阻塞导致的超时，但是这种情况我这并没有稳定复现的条件没办法排查以及避免

**Comment by teble** [comment]
但是至少在我手机上看，这种超时情况基本没发生过。可以考虑给予自启动，后台加锁，电池优化白名单这些有助于缓解手机强制休眠的情况发生

**Comment by junzhaoei** [comment]
> 但是至少在我手机上看，这种超时情况基本没发生过。可以考虑给予自启动，后台加锁，电池优化白名单这些有助于缓解手机强制休眠的情况发生

刚刚给了这些功能，0点时能正常打卡和签到，没有出现执行失败的问题了，谢谢大佬
