### ISSUE TITLE
情侣空间更新亲密空间，无法自动打卡

### ISSUE THREAD

**Issue by masterasd** [LuckyPray/XAutoDaily#106]
这个功能似乎将QQ原有的情侣空间变成了亲密空间类似于情侣的一个空间，是今年5-8月份更新的，希望作者能在闲暇时间段优化增加此功能。

thank 🎈✨

**Comment by teble** [comment]
情侣空间小程序入口还在，跟亲密空间是两个东西

**Comment by masterasd** [comment]
> 情侣空间小程序入口，亲密空间仍然是两个东西

原来如此，是我没了解相关问题，感谢作者能抽空回复此问题，最后还是希望未来的新版本可以增加此功能🥰✨
致谢
