### ISSUE TITLE
不支持最新TIM 4.0.95

### ISSUE THREAD

**Issue by StillMisty** [LuckyPray/XAutoDaily#112]
![image](https://github.com/user-attachments/assets/39dcb4a6-bd52-483d-bc74-b46202f76945)

**Comment by StillMisty** [comment]
但可以直接点桌面的图标运行

**Comment by teble** [comment]
> 但可以直接点桌面的图标运行

模块更新前临时使用 模块本体-TIM 跳转方式进入模块设置页面

**Comment by teble** [comment]
已适配
