### ISSUE TITLE
QQ9.1.15，打不开xa设置，QQ软件内部也找不到xa设置

### ISSUE THREAD

**Issue by SteveWorkshop** [LuckyPray/XAutoDaily#115]
如题，系统为Google aosp原版系统，QQ版本9.1.15，xa可以启动但是打不开QQ内设置，尝试禁用QA模块后仍然无法解决。本人QQ已经无法降级回8.9了

**Comment by coolxy** [comment]
同样打不开

**Comment by teble** [comment]
模块QQ全版本通杀，如果是a15但是框架不适配a15会有bug，框架问题自行解决
