### ISSUE TITLE
小米升级Hyperos2之后xautodaily失效了

### ISSUE THREAD

**Issue by chunfengyao** [LuckyPray/XAutoDaily#119]
一打开QQ就Toast提示：Xautodaily: No Such method

**Comment by chunfengyao** [comment]
android15, [lsposed mod](https://github.com/mywalkb/LSPosed_mod/releases).

**Comment by chunfengyao** [comment]
`cat: /data/data/com.tencent.mobileqq/files/xa_log/log.txt`

没有产生任何日志信息。

**Comment by teble** [comment]
自行使用支持 a15 的框架再使用模块，非模块问题不接受反馈

**Comment by chunfengyao** [comment]
嗯，换了[这个](https://github.com/JingMatrix/LSPosed/releases)就好了。
