### ISSUE TITLE
无法配置

### ISSUE THREAD

**Issue by JJBOY697** [LuckyPray/XAutoDaily#18]
![Screenshot_20220415-231130](https://user-images.githubusercontent.com/103763988/163589709-180609a4-0aa5-49d0-9dc2-b542dd2e5aa2.jpg)
![Screenshot_2022-04-15-23-02-50](https://user-images.githubusercontent.com/103763988/163589753-e4e2b2e6-56d7-4d05-b0ca-ca6190383998.png)
附上链接 微云https://share.weiyun.com/YYj1SPKs

**Comment by teble** [comment]
历史久远，如果最新版还有问题再开新issue
