### ISSUE TITLE
群打卡签到

### ISSUE THREAD

**Issue by hmw886** [LuckyPray/XAutoDaily#22]
希望群打卡签到可以设定一个可以选择时间段签到的，比如A群需要在早上八点到八点半，下午两点到两点半签到，打开qq自动判断是不是在这个时间段，在这个时间段是否已经签过这个群了，没签到就签到。
希望大佬能做一下这个功能，谢谢！！

**Comment by teble** [comment]
由于当前实现原因，暂时只支持自定义一个时间，单独配置需要等待后续看看怎么实现
