### ISSUE TITLE
绿钻每日签到

### ISSUE THREAD

**Issue by Polarforest** [LuckyPray/XAutoDaily#24]
希望可以实现QQ音乐绿钻的每日签到![Screenshot_2022-06-29-01-04-44-784-edit_com.tencent.qqmusic.jpg](https://user-images.githubusercontent.com/84024443/176241649-44af8837-7cc4-4cac-8adb-e698ebde2fd2.jpg)

**Comment by lisao10086** [comment]
> 希望可以实现QQ音乐绿钻的每日签到![Screenshot_2022-06-29-01-04-44-784-edit_com.tencent.qqmusic.jpg](https://user-images.githubusercontent.com/84024443/176241649-44af8837-7cc4-4cac-8adb-e698ebde2fd2.jpg)

**Comment by teble** [comment]
由于我没有绿钻所以无法编写配置，如果可以的话你可以提供抓包数据给我，验证后我会对配置进行更新

**Comment by teble** [comment]
配置v22已经支持
