### ISSUE TITLE
如何修改异步群发消息的间隔

### ISSUE THREAD

**Issue by Stfrostec** [LuckyPray/XAutoDaily#33]
昨天由于xautodaoly挂在后台（我又墓碑qq导致无法收发聊天记录），恢复qq时续火消息同时发出导致qq被检测到
还有，被禁言的群消息列表仍有续火消息，只不过有红色感叹号，这样的消息不会同时发出
所以有没有什么方法修改这种发送消息的方式（检测当前有多少条消息待发送然后依次逐条发送）能避免被封，而不是提高间隔（追求效率）

**Comment by teble** [comment]
想了一下，没有好的方案解决这个问题，因为墓碑QQ只禁止了QQ的消息发送而不等同于QQ被系统休眠(所有线程停止运行)，模块无法得知第三方应用的行为，所以无法做出更优的判断。
