### ISSUE TITLE
反馈bug

### ISSUE THREAD

**Issue by yanhanv** [LuckyPray/XAutoDaily#35]
功能全部无效了，LSP1.8.3，QQ8.8.55
日志https://yanhanv.lanzouj.com/ixR0d09aa5af

**Comment by teble** [comment]
全部无效是什么意思，我看日志没啥问题啊

**Comment by yanhanv** [comment]
实际上没有效果

**Comment by teble** [comment]
协议签到没效果是吧，例如点赞这种

**Comment by yanhanv** [comment]
点赞没有效，群打卡也不行

**Comment by yanhanv** [comment]
我就只关注了这两个

**Comment by teble** [comment]
小部分用户确实有这个问题（协议请求发不出去），可能得后面重写这一块，目前查不出什么导致的

**Comment by yanhanv** [comment]
就今天出现这个问题，昨天都是好好的

**Comment by teble** [comment]
这样的话，你长按两个任务，重置一下执行时间，可能是今天签到的时候炸了

**Comment by teble** [comment]
因为目前没有获取回调，所以不能判断执行是否成功，后面重写这一块应该能解决

**Comment by yanhanv** [comment]
重置了一下，确实正常能用了。

**Comment by yanhanv** [comment]
作者大大，辛苦了。
(⑉°з°)-♡

**Comment by teble** [comment]
那就可能刚好是凌晨的时候，协议请求没发出去导致的

**Comment by teble** [comment]
日志链接记得取消分享
