### ISSUE TITLE
初始化功能，groupsignlnmanager失败

### ISSUE THREAD

**Issue by shudaningmeng** [LuckyPray/XAutoDaily#36]
![Screenshot_20220814_220347_com tencent mobileqq](https://user-images.githubusercontent.com/111226611/184540605-0d6e46ba-5720-45d0-8fbf-b300b08de7ef.jpg)

**Comment by teble** [comment]
QQ低版本没有这个类

**Comment by teble** [comment]
问一下，qq版本是多少，刚刚发现dexkit有一个bug，可能导致查找类失败（不确定是不是这个问题）

**Comment by shudaningmeng** [comment]
QQ版本是8.9.2换了QQ和xa最新版使用正常了发自我的手机-------- 原始邮件 --------发件人： 韵の祈 ***@***.***>日期： 2022年8月22日周一 上午10:54收件人： LuckyPray/XAutoDaily ***@***.***>抄送： shudaningmeng ***@***.***>, Author ***@***.***>主    题： Re: [LuckyPray/XAutoDaily] 初始化功能，groupsignlnmanager失败 (Issue #36)

问一下，qq版本是多少，刚刚发现dexkit有一个bug，可能导致查找类失败（不确定是不是这个问题）

**Comment by teble** [comment]
ok
