### ISSUE TITLE
可以考虑一下增加每天QQ等级提速吗

### ISSUE THREAD

**Issue by catalpa0** [LuckyPray/XAutoDaily#40]
QQ新出的加速功能，每天发一条私密说说和小世界视频，可以加速QQ等级
![Uploading Screenshot_20220905-215109_QQ.png…]()

**Comment by catalpa0** [comment]
![Screenshot_20220905-215109_QQ](https://user-images.githubusercontent.com/112880367/188540299-77419a9b-5e2b-45d2-9a44-761225030b9c.png)

**Comment by xiaotian2333** [comment]
还有每天加3到4个好友，每个好友0.5天。进入qq小窝（随机出现，如果出现只需加3次好友）0.5天。加的好友可以是qq官方的机器人，如下：
~~~ 添加好友的链接
BabyQ：https://web.qun.qq.com/qunrobot/data.html?robot_uin=66600000

小冰：https://web.qun.qq.com/qunrobot/data.html?robot_uin=2854196306

赞噢机器人：https://web.qun.qq.com/qunrobot/data.html?robot_uin=2854204259

小店助手：https://web.qun.qq.com/qunrobot/data.html?robot_uin=2854196925
~~~
可以加完就删，也可以到第二天删了然后加回来

**Comment by xiang473535976** [comment]
感谢    可以考虑下楼上的qq等级提速

**Comment by teble** [comment]
down on v3.0.16
