### ISSUE TITLE
[Bug]群打卡任务执行失败

### ISSUE THREAD

**Issue by ZoruaFox** [LuckyPray/XAutoDaily#44]
自动执行与手动执行均失败，日志见下(为手动执行日志)
https://pastebin.com/ygnmX80q

**Comment by ZoruaFox** [comment]
![Screenshot_20220920_104739_com tencent mobileqq](https://user-images.githubusercontent.com/96456728/191156301-5815bfd2-2eaf-4f2b-abae-30e476b01fbd.jpg)
这个是设置的变量，但是貌似日志里显示用户设置变量时数为0

**Comment by teble** [comment]
8.9.10群打卡炸掉了，还没空修

**Comment by teble** [comment]
3.0.9已修
