### ISSUE TITLE
[BUG]3.0.11群打卡任务执行失败

### ISSUE THREAD

**Issue by ZoruaFox** [LuckyPray/XAutoDaily#46]
设备信息：Huawei Mate 40 Pro (Harmony OS 3.0.0.154)

框架类型及版本：Taichi 青钢影 10.1.0.10141326-8621

XAutoDaily版本：3.0.11(22102305)

宿主版本：8.9.15(3384)

配置版本：23

怀疑是太极的问题，相关报错信息如下：

https://pastebin.com/2BZET0ut

(还是剪贴板网站好用)

**Comment by teble** [comment]
3.0.11可能因为R8混淆弄坏了一部分代码，更新最新的3.0.11-fix应该就好了
