### ISSUE TITLE
[BUG]3.0.11版本无法群打卡

### ISSUE THREAD

**Issue by 2053628642** [LuckyPray/XAutoDaily#47]
设备 Redmi K50G MIUI 13.0.9
QQ 8.8.88(2770)
模块 3.0.11(22102305)
框架 LSPosed 1.6.4(6609)
XA降级3.0.9版本后可正常使用

**Comment by teble** [comment]
309之后未对群打卡逻辑进行任何修改，请检查日志，我这正常

**Comment by 2053628642** [comment]
https://wwp.lanzoup.com/iOPCE0etcwad

**Comment by teble** [comment]
看起来是3.0.11的R8弄坏了一些东西，没想通为什么，但是你更新3.0.11-fix应该就好了

**Comment by teble** [comment]
Repeated #48
