### ISSUE TITLE
[BUG]3.0.11-fix无法群打卡

### ISSUE THREAD

**Issue by 2053628642** [LuckyPray/XAutoDaily#48]
设备 Redmi K50G MIUI 13.0.9
框架 LSPosed 1.6.4(6609)
QQ 8.8.88(2770)
模块 3.0.11-fix(22102312)
日志
https://wwp.lanzoup.com/iKL1M0ethpgh

**Comment by teble** [comment]
没有无法打卡的日志记录

**Comment by teble** [comment]
我实测3.0.11确实存在那个问题，但是3.0.11-fix好了，你长按任务卡片重置后再执行一次应该不会有提示错误的信息了

**Comment by 2053628642** [comment]
切换账号后能正常使用了，刚刚的测试只是在已打卡的群上面添加几个未打卡的群

**Comment by teble** [comment]
长按任务卡片就能重置任务(
