### ISSUE TITLE
QQ内打开模块设置返回时无法正常返回

### ISSUE THREAD

**Issue by moxidev** [LuckyPray/XAutoDaily#5]
rt
返回时前往的是一个新的activity

QQ:8.8.68
模块:3.0.0-rc4
Android 12
框架 Lsposed
thanks !

**Comment by teble** [comment]
是点左上角的返回吧，应该不是系统返回，那个是我写漏了

**Comment by moxidev** [comment]
> 是点左上角的返回吧，应该不是系统返回，那个是我写漏了

啊对就是这个

**Comment by teble** [comment]
左上角返回干掉了（监听太麻烦
