### ISSUE TITLE
守护进程

### ISSUE THREAD

**Issue by AmanoHinaSan** [LuckyPray/XAutoDaily#55]
守护进程是什么，MIUI14上启动没反应

**Comment by teble** [comment]
仅提供QQ保活功能，需要搭配Shizuku使用，非必要选项

**Comment by AmanoHinaSan** [comment]
> 仅提供QQ保活功能，需要搭配Shizuku使用，非必要选项

已启用Shizuku的情况下依旧无法打开

**Comment by teble** [comment]
shizuku版本是最新的吗

**Comment by AmanoHinaSan** [comment]
> shizuku版本是最新的吗

已解决，我没打开是否启用shizuku保活机制按钮，打开就行了
