### ISSUE TITLE
关于自动加好友任务的建议

### ISSUE THREAD

**Issue by xiaotian2333** [LuckyPray/XAutoDaily#58]
建议将自动加好友的`小店助手机器人`换成`饭团团机器人`，这个机器人添加的时候没有信息。

这样加好友的时候就只有一条信息了 ~~（官方啥时候在出个没信息的呢）~~

```
饭团团：https://web.qun.qq.com/qunrobot/data.html?robot_uin=2854211892
```

**Comment by teble** [comment]
这个会改，在那之前可以考虑一下是否能通过接口添加群聊专属机器人，暂时还没时间测试，反正目前都会有消息弹，等测完了再说

**Comment by Hakuin123** [comment]
同求这个！`QQ小店助手`和`赞哦机器人`添加好友时都有好友新消息提醒，而`Baby Q`和`小冰`没有新好友提醒

根据任务描述，貌似只需要加一位好友就可以完成任务？

**Comment by teble** [comment]
> 同求这个！`QQ小店助手`和`赞哦机器人`添加好友时都有好友新消息提醒，而`Baby Q`和`小冰`没有新好友提醒
> 
> 根据任务描述，貌似只需要加一位好友就可以完成任务？

人数不固定，但是最多是4个

**Comment by xiaotian2333** [comment]
> > 同求这个！和添加好友时都有好友新消息提醒，而和没有新好友提醒`QQ小店助手``赞哦机器人``Baby Q``小冰`
> > 根据任务描述，貌似只需要加一位好友就可以完成任务？
> 
> 人数不固定，但是最多是4个

是不固定，但是要加速到满得4个才行
