### ISSUE TITLE
虚拟按键模式布局显示不完整

### ISSUE THREAD

**Issue by luckyzyx** [LuckyPray/XAutoDaily#6]
页面尾部最后一项，比如那个请作者吃辣条，只显示一半，签到设置里也是
3.0.0 rc8

**Comment by teble** [comment]
> 页面尾部最后一项，比如那个请作者吃辣条，只显示一半，签到设置里也是 3.0.0 rc8

虚拟导航栏暂未适配

**Comment by teble** [comment]
rc9已发布，已适配虚拟导航栏
