### ISSUE TITLE
[Bug]加好友活跃 反复执行

### ISSUE THREAD

**Issue by Hakuin123** [LuckyPray/XAutoDaily#63]
如图所示

![Screenshot_20230418_000637_com tencent mobileqq](https://user-images.githubusercontent.com/108911712/232545199-a89682a1-2c38-458a-a952-8f58f8d22426.jpg)

模块功能多次添加好友，但是没有解除好友关系（删除好友），同时任务提示未完成并反复尝试

**Comment by teble** [comment]
提供一下模块执行日志

**Comment by Hakuin123** [comment]
[XAutoDaily_2023-04-18T06_27_24.103.zip](https://github.com/LuckyPray/XAutoDaily/files/11256378/XAutoDaily_2023-04-18T06_27_24.103.zip)

**Comment by Hakuin123** [comment]
嘶…有的时候是在QQ主程序前台运行的情况下发生的…？

**Comment by teble** [comment]
日志看没有看到这种情况，都是回调还没执行完毕就被杀导致任务执行状态没保存

**Comment by teble** [comment]
有可能是你刚切后台就被杀了，然后接着重启了，在你看来觉得QQ一直存活的？

**Comment by Hakuin123** [comment]
> 有可能是你刚切后台就被杀了，然后接着重启了，在你看来觉得QQ一直存活的？

这样吗，有的时候好像确实是这样的…

那么…问题应该解决啦？谢谢哇w
