### ISSUE TITLE
请求适配QQ8.9.63

### ISSUE THREAD

**Issue by TFTree** [LuckyPray/XAutoDaily#68]
手滑升级了最新的QQ版本更新，就用不了了，每次打开QQ就会出现很多报错。

![_889070388__40f0171eb229a2a9237204790be3b41a_-1880047489_Screenshot_2023-06-18-15-02-26-04_9d26c6446fd7bb8e41d99b6262b17def_0_wifi_0](https://github.com/LuckyPray/XAutoDaily/assets/83645868/5fcbed53-f4cf-47f5-8f06-6efddc5ae753)

**Comment by teble** [comment]
四月份的时候就已经适配了，但是因为我没有资格加上nt正式版没发布就没在github发release：https://t.me/XAutoDaily/141

**Comment by TFTree** [comment]
> 四月份的时候就已经适配了，但是因为我没有资格加上nt正式版没发布就没在github发release：https://t.me/XAutoDaily/141

感谢！
