### ISSUE TITLE
字符抽不出来

### ISSUE THREAD

**Issue by hanhao05** [LuckyPray/XAutoDaily#70]
QQ版本8.9.50(3898)
模块版本3.0.17(23031218)
配置版本是31
机型红米k50ultra
会提示字符抽取失败

[XAutoDaily_2023-06-28T21_09_47.251.zip](https://github.com/LuckyPray/XAutoDaily/files/11895057/XAutoDaily_2023-06-28T21_09_47.251.zip)

**Comment by teble** [comment]
Duplicate of #69
