### ISSUE TITLE
个性标签自动点赞

### ISSUE THREAD

**Issue by Bcake123** [LuckyPray/XAutoDaily#8]
希望作者大大可以增加一个个人资料页面的个性标签自动点赞的功能 如图：
![Screenshot_20220218_102600](https://user-images.githubusercontent.com/98083630/154605956-a5a7e99a-eddb-4d66-84d9-c42cb0531fa9.jpg)

**Comment by teble** [comment]
这类功能并没有任何实质性的意义，第一并不是大众的需求，所以别人并不一定会接受你提出的功能，第二入口太隐蔽一般人根本不会看，第三这东西并不能带来等级/成长值的提升，只是单纯自己觉得数字好看而已，第四浪费流量(无论是服务器还是用户)
