### ISSUE TITLE
QQ音乐绿钻签到失效

### ISSUE THREAD

**Issue by StandGreat** [LuckyPray/XAutoDaily#81]
![Screenshot_2023-09-24-00-04-31-017_com.tencent.mobileqq.png](https://github.com/LuckyPray/XAutoDaily/assets/95478133/1de5e9f0-c96a-4b44-a5e3-73844a1f42f4)

模块中显示签到成功，但是获取的成长值为0，依旧可以在QQ音乐中手动签到

**Comment by teble** [comment]
成长任务已经失效，不再维护
