### ISSUE TITLE
超会QQ字符抽取必定失败

### ISSUE THREAD

**Issue by Emotion04** [LuckyPray/XAutoDaily#84]
有超级会员抽取qq字符抽取，只会成功2次，初步不是遗漏某人。
每个人只会抽两次，第三次是不成功的。无论是qq在前台还是后台时执行都会出现这个问题，每天必定如此。

[S31126-15481561_com.tencent.mobileqq.png](https://github.com/LuckyPray/XAutoDaily/assets/107828821/71520745-58f6-4c25-822b-54dc96ef269d)

**Comment by teble** [comment]
配置之前就已经修复了这个问题，现在关闭此iss
