### ISSUE TITLE
按步骤操作完后设置里找不到

### ISSUE THREAD

**Issue by azNagisa** [LuckyPray/XAutoDaily#89]
模块qq都重启过一边，qq设置里还是找不到

**Comment by tujianyuan1** [comment]
同样 是要下载shizuku好像才能用

**Comment by teble** [comment]
> 同样 是要下载shizuku好像才能用

shizuku 提供的功能跟 xp 模块功能没有任何关联，自行检查框架日志判断框架是否正常工作以及模块是否成功加载
