### ISSUE TITLE
XAutoDaily v3.0.26-fix 在QQ设置中不显示

### ISSUE THREAD

**Issue by xiangshaw** [LuckyPray/XAutoDaily#92]
环境说明：
太极 14.0.6.11231507
XAutoDaily v3.0.26-fix
QQ 9.0.56
问题反馈：
最新版本XAutoDaily v3.0.26 以及 XAutoDaily v3.0.26-fix 在QQ 9.0.56的设置中不显示，在XAutoDaily v3.0.25版本，能正常显示，现在已退回XAutoDaily v3.0.25版本使用。大佬有时间看看修复一下。

**Comment by teble** [comment]
太极已经关停服务器，模块新版本无法再上传适配

**Comment by xiangshaw** [comment]
原来是这样，感谢回复~
