### ISSUE TITLE
[Bug] 发送给好友的消息（可能）会被“吞”

### ISSUE THREAD

**Issue by EatHatsuneShallots** [LuckyPray/XAutoDaily#95]
QQ 版本：9.0.0

Android 版本：12S

模块版本：3.0.26-fix

Xposed 框架：NPatch 0.6.1

复现步骤：使用好友续火花功能

预期行为：消息不会被吞

实际行为：消息可能会被“吞”，且需要重启 QQ 才会显示

补充说明：QA 的语音转发也有类似的问题，应该是通病

**Comment by teble** [comment]
吞消息是nt qq本身的bug，其它端可以正常看见

**Comment by EatHatsuneShallots** [comment]
> 吞消息是nt qq本身的bug，其它端可以正常看见

这个我知道，但是只有私聊才会有这个问题，群聊没有这个问题

**Comment by teble** [comment]
这个问题跟模块无关，后台发送可能会触发

**Comment by EatHatsuneShallots** [comment]
> 这个问题跟模块无关，后台发送可能会触发

后台是指 QQ 在后台运行，还是指直接的 API 调用
QQ 在前台（在前台可见）仍会有这个问题

**Comment by teble** [comment]
指通过非UI交互触发的发送消息

**Comment by teble** [comment]
尝试更新 3.0.27 后是看看否还会发生此问题

**Comment by EatHatsuneShallots** [comment]
解决了
