### ISSUE TITLE
[Bug] 群打卡在登录后的一段时间无法使用

### ISSUE THREAD

**Issue by EatHatsuneShallots** [LuckyPray/XAutoDaily#98]
因为突然提示版本过低，所以被迫用上 9.0.60
但是群签到用不了，日志提示执行群签到 xxx 超时（疑似是 Cookie 过期）

**Comment by EatHatsuneShallots** [comment]
原来只是 Cookie 过期了

**Comment by teble** [comment]
版本不兼容的判断写的很粗糙，因为执行超时太多了就会触发通知提示，一般来说超时是凌晨后台挂机时手机系统压制了后台导致断网/线程执行被中断导致的。并非cookie过期，一般手动恢复前台后会自动重试

**Comment by EatHatsuneShallots** [comment]
> 一般来说超时是凌晨后台挂机时手机系统压制了后台导致断网/线程执行被中断导致的。并非cookie过期

当时应用是在前台，且没有使用过群签到功能
使用后就正常了

**Comment by teble** [comment]
群签到是直接发的协议包，如果协议包的token是旧的表现现象应该是所有功能都出现问题，例如：消息

**Comment by teble** [comment]
超时的另一种可能是服务端响应超时了，目前是好像是超过10s没有回调就会判断超时

**Comment by teble** [comment]
超时这个现象会提示不兼容，后面大版本更新会改善掉，目前是可以忽略掉的因为会重试

**Comment by EatHatsuneShallots** [comment]
> 如果协议包的token是旧的表现现象应该是所有功能都出现问题

当时只有某些（正在使用的）功能出现了问题：群签到、资料卡回赞（获取点赞列表超时）、好友点赞
好友抽取幸运字符无影响

**Comment by EatHatsuneShallots** [comment]
> 超时这个现象会提示不兼容，后面大版本更新会改善掉，目前是可以忽略掉的因为会重试

当时是试过两次的（长按功能清除执行记录）

**Comment by teble** [comment]
协议超时这个比较玄乎，我这边没有复现条件不好排查

**Comment by teble** [comment]
如果下次再复现可以试试强制停止qq后重试？不确定是不是发包链路上某个地方阻塞了

**Comment by teble** [comment]
但是可以肯定的是并非token过期导致的

**Comment by EatHatsuneShallots** [comment]
> 协议超时这个比较玄乎，我这边没有复现条件不好排查

可以尝试使设备异常下线（需要重新输入密码的那种），然后重新登录后立即使用模块
